# Generated by Django 3.2.5 on 2021-08-01 06:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='form',
            field=models.CharField(choices=[('OFFICAL_STAFF', 'Nhân viên chính thức'), ('INTERN', 'Thực tập viên')], default='Nhân viên chính thức', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Nhà tuyển dụng'), ('CANDIDATE', 'Người ứng tuyển')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('NEUTRAL', 'Giới tính khác')], default='Nam', max_length=20, null=True),
        ),
    ]
