# Generated by Django 3.2.5 on 2021-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_recruitment_criteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recruiter',
            new_name='commented',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='candidate',
            new_name='commenter',
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='criteria',
            field=models.ManyToManyField(blank=True, null=True, related_name='recruitment_criteria', to='jobs.Criteria'),
        ),
    ]
